### ISSUE TITLE
OpenBSD patches

### ISSUE THREAD

**Issue by greydot** [corecode/rcsparse#1]
Hi
There are some patches [1](http://anoncvs.estpak.ee/cgi-bin/cgit/openbsd-ports/tree/devel/py-rcsparse/patches) from openbsd you might wanna take a look at. One of them fixes a segmentation fault when parsing RCS files.

**Comment by corecode** [comment]
are there any other patches that should be merged?

**Comment by greydot** [comment]
Not that I know of, no.
