### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by jpouellet** [corecode/rcsparse#3]
I wish to add rcsparse to [MacPorts](https://www.macports.org/) so that I may use [git-cvs](https://github.com/ustuehler/git-cvs) (for which it is a dependency).

However, it seems the original page distributing [releases](http://ww2.fs.ei.tum.de/~corecode/hg/rcsparse) is no more. It seems ww2.fs.ei.tum.de does not even have a DNS entry anymore.

Are you hosting releases someplace else?

Thanks!

**Comment by jpouellet** [comment]
Also, I originally asked you this via email, but it bounced back to me. From the headers it looked like ipv6 issues. ¯\_(ツ)_/¯

**Comment by jpouellet** [comment]
I should also note that gitorious is dead and not coming back.

**Comment by corecode** [comment]
please use github's source tree tgz feature
